// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using windowswebgsm.Data;

namespace windowswebgsm.Data.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20211021234932_CreateServerDB")]
    partial class CreateServerDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("windowswebgsm.Data.Models.Server", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AutoRestart")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("bit");

                    b.Property<bool>("BackupOnStart")
                        .HasColumnType("bit");

                    b.Property<string>("FormattedUptime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PID")
                        .HasColumnType("int");

                    b.Property<int>("Players")
                        .HasColumnType("int");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("QueryPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SteamID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UpdateOnStart")
                        .HasColumnType("bit");

                    b.Property<int>("Uptime")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
